services:

  prometheus-destination:
    image: prom/prometheus:latest
    container_name: prometheus-destination
    command:
      - --web.enable-remote-write-receiver
      - --config.file=/etc/prometheus/prometheus.yml
    volumes:
      - ./prometheus-destination.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9091:9090"

  grafana-alloy: 
    image: grafana/alloy:latest
    container_name: grafana-alloy
    volumes:
      - ./alloy-data:/var/lib/alloy/data
      - ./config.alloy:/etc/alloy/config.alloy
      - ./grafana-agent.yml:/etc/agent/agent.yml
    command:
      - run
      - --server.http.listen-addr=0.0.0.0:12345
      - --storage.path=/var/lib/alloy/data
      - /etc/alloy/config.alloy
    ports:
      - "12345:12345"

  #grafana-agent:
  #  image: grafana/agent:latest
  #  container_name: grafana-agent
  #  volumes:
  #    - ./grafana-agent.yml:/etc/agent/agent.yml
  #  command:
  #    - --config.file=/etc/agent/agent.yml
  #    - --metrics.wal-directory=/etc/agent/data
  #    - -server.http.address=0.0.0.0:12345
  #  ports:
  #    - "12345:12345" # Update with Grafana Agent's desired endpoint

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - grafana-data:/var/lib/grafana
      - ./grafana-provisioning:/etc/grafana/provisioning
    ports:
      - "3000:3000"

volumes:
  prometheus-data-destination:
  grafana-data: